// Smoke tests for the frontend test toolchain itself (T2):
//  - Vitest runs, jsdom provides a DOM, RTL renders, jest-dom matchers work.
//  - The OpenAPI→TS codegen produced schema.ts covering the backend's routes.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { render, screen } from '@testing-library/react'

describe('test toolchain', () => {
  it('renders a React element into jsdom and matches with jest-dom', () => {
    render(<div data-testid="probe">ki-mcp-pcb</div>)
    const node = screen.getByTestId('probe')
    expect(node).toBeInTheDocument()
    expect(node).toHaveTextContent('ki-mcp-pcb')
  })
})

describe('OpenAPI→TS codegen output', () => {
  // Vitest runs with cwd at the package root (where vite.config.ts lives).
  const readSchema = (): string =>
    readFileSync(resolve(process.cwd(), 'src/api/schema.ts'), 'utf-8')

  it('was generated by openapi-typescript', () => {
    const schema = readSchema()
    expect(schema).toContain('auto-generated by openapi-typescript')
    expect(schema).toContain('export interface paths')
  })

  it('covers the working-CIR endpoint from the backend', () => {
    expect(readSchema()).toContain('/api/cir')
  })
})
