// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A schematic bus — a labeled group of related nets.
 */
export type Bus = { uuid: string, sheet_uuid: string, name: string, points_mm: Array<[number, number]>, members: Array<string>, };
