// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declared differential pair.
 */
export type DiffPair = { 
/**
 * Display name (e.g. `"USB_D"`, `"MDIO_TRD0"`).
 */
name: string, 
/**
 * Net name of the positive leg.
 */
net_positive: string, 
/**
 * Net name of the negative leg.
 */
net_negative: string, 
/**
 * Target differential impedance in ohms (90 for USB 2.0,
 * 100 for LVDS / Ethernet, 85 for SATA, …). `0.0` = unspecified.
 */
target_impedance_ohms: number, 
/**
 * Target trace-to-trace gap in mm. `0.0` = unspecified
 * (the solver picks one).
 */
target_gap_mm: number, 
/**
 * Optional length-match group this pair belongs to. Empty if
 * the pair isn't grouped.
 */
length_group: string, 
/**
 * Optional per-pair length-skew tolerance (mm). The legs of a
 * diff pair are typically matched to ≤ 5 mil = 0.127 mm.
 */
skew_tolerance_mm: number, };
