// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerRef } from "./LayerRef";

/**
 * Non-conductive graphics: silkscreen, fab, courtyard.
 */
export type Drawing = { uuid: string, layer: LayerRef, kind: string, points_mm: Array<[number, number]>, width_mm: number, text: string, };
