// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerRef } from "./LayerRef";

/**
 * Non-conductive graphics: silkscreen, fab, courtyard.
 */
export type Drawing = { uuid: string, layer: LayerRef, 
/**
 * `gr_line`, `gr_arc`, `gr_rect`, `gr_circle`, `gr_text`,
 * `fp_line`, `fp_text` (when inside a footprint).
 */
kind: string, points_mm: Array<[number, number]>, width_mm: number, text: string, };
