// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FabTargetPreset } from "./FabTargetPreset";

/**
 * A named fab-target preset (e.g. JLCPCB 2-layer green HASL).
 */
export type FabTarget = { preset: FabTargetPreset, min_trace_mm: number, min_space_mm: number, min_drill_mm: number, min_annular_ring_mm: number, layer_count: number, soldermask_color: string, silkscreen_color: string, finish: string, };
