// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Built-in fab presets.
 */
export type FabTargetPreset = "jlcpcb" | "oshpark" | "pcbway" | "generic";
