// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerRef } from "./LayerRef";

/**
 * An instance of a library footprint placed on the board.
 */
export type FootprintInstance = { uuid: string, refdes: string, lib_id: string, value: string, mpn: string, layer: LayerRef, position_mm: [number, number], rotation_deg: number, locked: boolean, };
