// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Drawing } from "./Drawing";
import type { FootprintCourtyard } from "./FootprintCourtyard";
import type { LayerRef } from "./LayerRef";
import type { Model3D } from "./Model3D";
import type { Pad } from "./Pad";

/**
 * An instance of a library footprint placed on the board.
 */
export type FootprintInstance = { uuid: string, refdes: string, lib_id: string, value: string, mpn: string, layer: LayerRef, position_mm: [number, number], rotation_deg: number, locked: boolean, 
/**
 * `(attr …)` flags — `smd`, `through_hole`, `exclude_from_pos_files`,
 * `exclude_from_bom`. Empty if the source omitted the form.
 */
attributes: Array<string>, 
/**
 * All `(pad …)` entries belonging to this footprint, in declaration
 * order. M2-R-01 populates these from the source S-expression.
 */
pads: Array<Pad>, 
/**
 * Courtyard polygon on `F.CrtYd` / `B.CrtYd`. Used by the M2-R-06
 * DRC kernel's courtyard-collision check.
 */
courtyard: FootprintCourtyard | null, 
/**
 * `(model "<path>" (offset …) (scale …) (rotate …))` blocks. We
 * preserve them for round-trip but the schematic/PCB editors don't
 * touch them.
 */
models_3d: Array<Model3D>, 
/**
 * Free-form silkscreen / fab annotations inside the footprint, kept
 * for round-trip fidelity.
 */
drawings: Array<Drawing>, };
