// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerRef } from "./LayerRef";

/**
 * Footprint courtyard polygon (F.CrtYd or B.CrtYd).
 */
export type FootprintCourtyard = { layer: LayerRef, points_mm: Array<[number, number]>, 
/**
 * Optional line width in mm.
 */
width_mm: number, };
