// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wire junction (T or +) — required when a wire crosses or branches.
 */
export type Junction = { uuid: string, sheet_uuid: string, position_mm: [number, number], };
