import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import type {
  BomPolicy,
  Bus,
  DesignRules,
  Drawing,
  FabTarget,
  FabTargetPreset,
  FootprintInstance,
  Junction,
  Label,
  LabelKind,
  Layer,
  LayerRef,
  LibSymbol,
  LibraryEntry,
  LibraryTable,
  Net,
  NetClass,
  NetClassRef,
  NetRef,
  NoConnect,
  Outline,
  PadRef,
  Pcb,
  Project,
  ProjectMetadata,
  Schematic,
  Sheet,
  SheetPin,
  Stackup,
  StackupLayer,
  StackupLayerKind,
  SymbolInstance,
  SymbolProperty,
  Topology,
  Track,
  Via,
  Wire,
  Zone,
} from "./index";

// ---------------------------------------------------------------------------
// Filesystem-driven barrel completeness
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const KCIR_DIR = dirname(__filename);
// KCIR_DIR is `<repo>/client/src/lib/kcir`. Up four levels lands on
// `<repo>` (kiclaude), which contains the on-disk examples.
const REPO_ROOT = resolve(KCIR_DIR, "..", "..", "..", "..");
const BLINKY_DIR = resolve(REPO_ROOT, "examples", "blinky");

function listKcirSources(): string[] {
  return readdirSync(KCIR_DIR)
    .filter(
      (name) =>
        name.endsWith(".ts") &&
        !name.endsWith(".test.ts") &&
        name !== "index.ts",
    )
    .sort();
}

function readIndex(): string {
  return readFileSync(resolve(KCIR_DIR, "index.ts"), "utf8");
}

describe("kcir/index.ts barrel", () => {
  const files = listKcirSources();

  it("finds the full KCIR file set on disk", () => {
    // Sanity-check the discovery — if this number ever changes the
    // ts-rs generator added or dropped a type and the rest of this
    // file needs auditing.
    expect(files.length).toBe(38);
  });

  it.each(files)("index.ts re-exports %s", (filename) => {
    const stem = filename.replace(/\.ts$/, "");
    const indexSource = readIndex();
    // Match both `export type { X }` and `export { X }` forms.
    const pattern = new RegExp(
      `export\\s+(?:type\\s+)?\\{[^}]*\\b${stem}\\b[^}]*\\}\\s+from\\s+"\\./${stem}"`,
    );
    expect(indexSource).toMatch(pattern);
  });

  it.each(files)("%s file is non-empty and has the ts-rs banner", (filename) => {
    const src = readFileSync(resolve(KCIR_DIR, filename), "utf8");
    expect(src.length).toBeGreaterThan(0);
    expect(src).toMatch(/generated by \[ts-rs\]/);
  });
});

// ---------------------------------------------------------------------------
// Per-type compile-time fixtures
//
// Each fixture declares a `const … : Type = { … }` so TypeScript enforces
// shape at compile time; the runtime test verifies every documented key is
// physically present (catches accidental optionals slipping into the
// generator without an explicit migration).
// ---------------------------------------------------------------------------

function assertKeys<T extends object>(actual: T, expected: readonly (keyof T)[]) {
  for (const key of expected) {
    expect(actual).toHaveProperty(String(key));
  }
}

describe("BomPolicy", () => {
  const fx: BomPolicy = {
    preferred_distributors: ["Digikey", "Mouser"],
    max_unit_price_usd: 1.25,
    require_in_stock: true,
    require_jlc_assembly: false,
    region: "US",
  };
  it("has every documented key", () => {
    assertKeys(fx, [
      "preferred_distributors",
      "max_unit_price_usd",
      "require_in_stock",
      "require_jlc_assembly",
      "region",
    ]);
  });
  it("allows null max_unit_price_usd", () => {
    const open: BomPolicy = { ...fx, max_unit_price_usd: null };
    expect(open.max_unit_price_usd).toBeNull();
  });
});

describe("Bus", () => {
  const fx: Bus = {
    uuid: "11111111-1111-1111-1111-111111111111",
    sheet_uuid: "22222222-2222-2222-2222-222222222222",
    name: "ADDR[7:0]",
    points_mm: [
      [10, 20],
      [30, 20],
    ],
    members: ["ADDR0", "ADDR1", "ADDR2"],
  };
  it("has every documented key", () => {
    assertKeys(fx, ["uuid", "sheet_uuid", "name", "points_mm", "members"]);
  });
});

describe("DesignRules", () => {
  const fx: DesignRules = {
    clearance_mm: 0.2,
    trace_width_mm: 0.25,
    via_drill_mm: 0.3,
    via_diameter_mm: 0.6,
    uvia_drill_mm: 0.1,
    uvia_diameter_mm: 0.2,
    allow_microvias: false,
    allow_blind_buried_vias: false,
  };
  it("has every documented key", () => {
    assertKeys(fx, [
      "clearance_mm",
      "trace_width_mm",
      "via_drill_mm",
      "via_diameter_mm",
      "uvia_drill_mm",
      "uvia_diameter_mm",
      "allow_microvias",
      "allow_blind_buried_vias",
    ]);
  });
});

describe("Drawing", () => {
  const fx: Drawing = {
    uuid: "33333333-3333-3333-3333-333333333333",
    layer: "F.SilkS" satisfies LayerRef,
    kind: "gr_line",
    points_mm: [
      [0, 0],
      [10, 0],
    ],
    width_mm: 0.15,
    text: "",
  };
  it("has every documented key", () => {
    assertKeys(fx, [
      "uuid",
      "layer",
      "kind",
      "points_mm",
      "width_mm",
      "text",
    ]);
  });
});

describe("FabTargetPreset and FabTarget", () => {
  it("allows every documented preset string", () => {
    const presets: FabTargetPreset[] = [
      "jlcpcb",
      "oshpark",
      "pcbway",
      "generic",
    ];
    expect(presets).toHaveLength(4);
  });

  it("FabTarget has every documented key", () => {
    const fx: FabTarget = {
      preset: "jlcpcb",
      min_trace_mm: 0.127,
      min_space_mm: 0.127,
      min_drill_mm: 0.3,
      min_annular_ring_mm: 0.075,
      layer_count: 2,
      soldermask_color: "green",
      silkscreen_color: "white",
      finish: "HASL",
    };
    assertKeys(fx, [
      "preset",
      "min_trace_mm",
      "min_space_mm",
      "min_drill_mm",
      "min_annular_ring_mm",
      "layer_count",
      "soldermask_color",
      "silkscreen_color",
      "finish",
    ]);
  });
});

describe("FootprintInstance", () => {
  const fx: FootprintInstance = {
    uuid: "5c7e0a3e-4f9b-4ddc-9b3d-0001000000a1",
    refdes: "U1",
    lib_id: "MCU_Espressif:ESP32-S3-WROOM-1",
    value: "ESP32-S3-WROOM-1",
    mpn: "ESP32-S3-WROOM-1-N8",
    layer: "F.Cu",
    position_mm: [50, 50],
    rotation_deg: 0,
    locked: false,
  };
  it("has every documented key", () => {
    assertKeys(fx, [
      "uuid",
      "refdes",
      "lib_id",
      "value",
      "mpn",
      "layer",
      "position_mm",
      "rotation_deg",
      "locked",
    ]);
  });
});

describe("Junction", () => {
  const fx: Junction = {
    uuid: "44444444-4444-4444-4444-444444444444",
    sheet_uuid: "22222222-2222-2222-2222-222222222222",
    position_mm: [50, 50],
  };
  it("has every documented key", () => {
    assertKeys(fx, ["uuid", "sheet_uuid", "position_mm"]);
  });
});

describe("Label and LabelKind", () => {
  it("enumerates every label kind", () => {
    const kinds: LabelKind[] = ["local", "global", "hierarchical", "power"];
    expect(kinds).toHaveLength(4);
  });
  it("Label has every documented key", () => {
    const fx: Label = {
      uuid: "55555555-5555-5555-5555-555555555555",
      sheet_uuid: "22222222-2222-2222-2222-222222222222",
      kind: "global",
      text: "RESET",
      position_mm: [50, 50],
      rotation_deg: 0,
      shape: "bidirectional",
    };
    assertKeys(fx, [
      "uuid",
      "sheet_uuid",
      "kind",
      "text",
      "position_mm",
      "rotation_deg",
      "shape",
    ]);
  });
});

describe("Layer and LayerRef", () => {
  it("Layer has every documented key", () => {
    const fx: Layer = {
      id: 0,
      name: "F.Cu",
      kind: "signal",
      purpose: "user",
    };
    assertKeys(fx, ["id", "name", "kind", "purpose"]);
  });
  it("LayerRef is a string alias", () => {
    const ref: LayerRef = "F.Cu";
    expect(typeof ref).toBe("string");
  });
});

describe("LibraryEntry / LibraryTable", () => {
  const entry: LibraryEntry = {
    name: "Device",
    uri: "${KICAD9_SYMBOL_DIR}/Device.kicad_sym",
    kind: "KiCad",
    options: "",
    descr: "Generic devices",
  };
  it("LibraryEntry has every documented key", () => {
    assertKeys(entry, ["name", "uri", "kind", "options", "descr"]);
  });
  it("LibraryTable wraps symbol + footprint arrays", () => {
    const table: LibraryTable = { symbol_libs: [entry], footprint_libs: [] };
    expect(table.symbol_libs).toHaveLength(1);
    expect(table.footprint_libs).toHaveLength(0);
  });
});

describe("LibSymbol", () => {
  const fx: LibSymbol = {
    lib_id: "Device:R",
    properties: [],
    is_power: false,
  };
  it("has every documented key", () => {
    assertKeys(fx, ["lib_id", "properties", "is_power"]);
  });
});

describe("Net / NetClass / NetClassRef / NetRef / Topology / PadRef", () => {
  it("Topology accepts every documented variant", () => {
    const tops: Topology[] = ["daisy_chain", "fly_by", "star", "bus"];
    expect(tops).toHaveLength(4);
  });

  it("NetClass + Net + PadRef shapes", () => {
    const pad: PadRef = { refdes: "U1", pad: "7" };
    const cls: NetClass = {
      name: "Default",
      description: "Default class",
      clearance_mm: 0.2,
      trace_width_mm: 0.25,
      via_drill_mm: 0.3,
      via_diameter_mm: 0.6,
      diff_pair_width_mm: null,
      diff_pair_gap_mm: null,
    };
    const ref: NetClassRef = cls.name;
    const dpRef: NetRef = "USB-N";
    const net: Net = {
      name: "USB-P",
      class: ref,
      members: [pad],
      diff_pair: dpRef,
      power_rail: null,
      topology: "star",
      length_match_group: null,
      target_impedance_ohm: 50,
      reference_plane: "GND",
    };

    assertKeys(pad, ["refdes", "pad"]);
    assertKeys(cls, [
      "name",
      "description",
      "clearance_mm",
      "trace_width_mm",
      "via_drill_mm",
      "via_diameter_mm",
      "diff_pair_width_mm",
      "diff_pair_gap_mm",
    ]);
    assertKeys(net, [
      "name",
      "class",
      "members",
      "diff_pair",
      "power_rail",
      "topology",
      "length_match_group",
      "target_impedance_ohm",
      "reference_plane",
    ]);
  });
});

describe("NoConnect", () => {
  const fx: NoConnect = {
    uuid: "66666666-6666-6666-6666-666666666666",
    sheet_uuid: "22222222-2222-2222-2222-222222222222",
    position_mm: [25, 50],
    at: { refdes: "U1", pad: "12" },
  };
  it("has every documented key", () => {
    assertKeys(fx, ["uuid", "sheet_uuid", "position_mm", "at"]);
  });
});

describe("Outline", () => {
  const fx: Outline = {
    points_mm: [
      [0, 0],
      [100, 0],
      [100, 100],
      [0, 100],
    ],
    cutouts: [
      [
        [40, 40],
        [60, 40],
        [60, 60],
        [40, 60],
      ],
    ],
  };
  it("has every documented key", () => {
    assertKeys(fx, ["points_mm", "cutouts"]);
  });
});

describe("Pcb", () => {
  it("has every documented key", () => {
    const fx: Pcb = {
      version: 20240108,
      generator: "kiclaude",
      thickness_mm: 1.6,
      paper: "A4",
      pad_to_mask_clearance_mm: 0.0,
      layers: [{ id: 0, name: "F.Cu", kind: "signal", purpose: "user" }],
      footprints: [],
      tracks: [],
      vias: [],
      zones: [],
      outline: { points_mm: [], cutouts: [] },
      drawings: [],
      nets: [],
    };
    assertKeys(fx, [
      "version",
      "generator",
      "thickness_mm",
      "paper",
      "pad_to_mask_clearance_mm",
      "layers",
      "footprints",
      "tracks",
      "vias",
      "zones",
      "outline",
      "drawings",
      "nets",
    ]);
  });
});

describe("ProjectMetadata", () => {
  const fx: ProjectMetadata = {
    title: "blinky",
    revision: "0.1",
    company: "",
    date: "",
    comment_1: "",
    comment_2: "",
    comment_3: "",
    comment_4: "",
  };
  it("has every documented key", () => {
    assertKeys(fx, [
      "title",
      "revision",
      "company",
      "date",
      "comment_1",
      "comment_2",
      "comment_3",
      "comment_4",
    ]);
  });
});

describe("SymbolInstance and SymbolProperty", () => {
  const property: SymbolProperty = {
    key: "Reference",
    value: "U1",
    position_mm: [0, 0],
    rotation_deg: 0,
    hide: false,
  };

  const fx: SymbolInstance = {
    uuid: "77777777-7777-7777-7777-777777777777",
    sheet_uuid: "22222222-2222-2222-2222-222222222222",
    lib_id: "MCU_Espressif:ESP32-S3-WROOM-1",
    refdes: "U1",
    value: "ESP32-S3-WROOM-1",
    footprint: "MCU_Espressif:ESP32-S3-WROOM-1",
    mpn: "ESP32-S3-WROOM-1-N8",
    datasheet: "https://espressif.com",
    position_mm: [50, 50],
    rotation_deg: 0,
    mirrored: false,
    unit: 1,
    in_bom: true,
    on_board: true,
    dnp: false,
    is_power_flag: false,
    is_power_symbol: false,
    properties: [property],
  };

  it("SymbolProperty has every documented key", () => {
    assertKeys(property, [
      "key",
      "value",
      "position_mm",
      "rotation_deg",
      "hide",
    ]);
  });

  it("SymbolInstance has every documented key", () => {
    assertKeys(fx, [
      "uuid",
      "sheet_uuid",
      "lib_id",
      "refdes",
      "value",
      "footprint",
      "mpn",
      "datasheet",
      "position_mm",
      "rotation_deg",
      "mirrored",
      "unit",
      "in_bom",
      "on_board",
      "dnp",
      "is_power_flag",
      "is_power_symbol",
      "properties",
    ]);
  });
});

describe("Schematic / Sheet / SheetPin", () => {
  const pin: SheetPin = {
    uuid: "88888888-8888-8888-8888-888888888888",
    name: "RESET",
    shape: "input",
    position_mm: [10, 20],
    rotation_deg: 0,
  };
  const sheet: Sheet = {
    uuid: "5c7e0a3e-4f9b-4ddc-9b3d-000100000001",
    name: "blinky",
    file: "blinky.kicad_sch",
    parent: null,
    position_mm: [0, 0],
    size_mm: [0, 0],
    pins: [pin],
  };
  const sch: Schematic = {
    sheets: [sheet],
    symbols: [],
    wires: [],
    junctions: [],
    labels: [],
    no_connects: [],
    buses: [],
    lib_symbols: [],
  };
  it("SheetPin has every documented key", () => {
    assertKeys(pin, [
      "uuid",
      "name",
      "shape",
      "position_mm",
      "rotation_deg",
    ]);
  });
  it("Sheet has every documented key", () => {
    assertKeys(sheet, [
      "uuid",
      "name",
      "file",
      "parent",
      "position_mm",
      "size_mm",
      "pins",
    ]);
  });
  it("Schematic has every documented key", () => {
    assertKeys(sch, [
      "sheets",
      "symbols",
      "wires",
      "junctions",
      "labels",
      "no_connects",
      "buses",
      "lib_symbols",
    ]);
  });
});

describe("Stackup / StackupLayer / StackupLayerKind", () => {
  it("StackupLayerKind enumerates every documented variant", () => {
    const kinds: StackupLayerKind[] = [
      "copper",
      "dielectric",
      "soldermask",
      "silkscreen",
      "paste",
      "adhesive",
    ];
    expect(kinds).toHaveLength(6);
  });

  const layer: StackupLayer = {
    name: "F.Cu",
    kind: "copper",
    thickness_mm: 0.035,
    dielectric_constant: null,
    loss_tangent: null,
    color: "copper",
  };

  it("StackupLayer has every documented key", () => {
    assertKeys(layer, [
      "name",
      "kind",
      "thickness_mm",
      "dielectric_constant",
      "loss_tangent",
      "color",
    ]);
  });

  it("Stackup has every documented key", () => {
    const fx: Stackup = {
      layers: [layer],
      power_plane_layers: [],
      controlled_impedance: false,
      board_thickness_mm: 1.6,
      finish: "HASL",
    };
    assertKeys(fx, [
      "layers",
      "power_plane_layers",
      "controlled_impedance",
      "board_thickness_mm",
      "finish",
    ]);
  });
});

describe("Track / Via / Wire / Zone", () => {
  it("Track has every documented key", () => {
    const fx: Track = {
      uuid: "99999999-9999-9999-9999-999999999999",
      layer: "F.Cu",
      net: "GND",
      points_mm: [
        [10, 10],
        [20, 10],
      ],
      width_mm: 0.25,
    };
    assertKeys(fx, ["uuid", "layer", "net", "points_mm", "width_mm"]);
  });
  it("Via has every documented key", () => {
    const fx: Via = {
      uuid: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      net: "GND",
      position_mm: [10, 10],
      from_layer: "F.Cu",
      to_layer: "B.Cu",
      drill_mm: 0.3,
      diameter_mm: 0.6,
    };
    assertKeys(fx, [
      "uuid",
      "net",
      "position_mm",
      "from_layer",
      "to_layer",
      "drill_mm",
      "diameter_mm",
    ]);
  });
  it("Wire has every documented key", () => {
    const fx: Wire = {
      uuid: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
      sheet_uuid: "22222222-2222-2222-2222-222222222222",
      points_mm: [
        [0, 0],
        [10, 0],
      ],
    };
    assertKeys(fx, ["uuid", "sheet_uuid", "points_mm"]);
  });
  it("Zone has every documented key", () => {
    const fx: Zone = {
      uuid: "cccccccc-cccc-cccc-cccc-cccccccccccc",
      layer: "F.Cu",
      net: "GND",
      outline_mm: [
        [0, 0],
        [10, 0],
        [10, 10],
      ],
      thermal_relief: true,
    };
    assertKeys(fx, ["uuid", "layer", "net", "outline_mm", "thermal_relief"]);
  });
});

// ---------------------------------------------------------------------------
// Round-trip from the on-disk examples/blinky fixture.
// ---------------------------------------------------------------------------

describe("examples/blinky round-trip", () => {
  it("blinky fixture files exist on disk", () => {
    for (const f of [
      "blinky.kicad_pro",
      "blinky.kicad_pcb",
      "blinky.kicad_sch",
    ]) {
      const p = resolve(BLINKY_DIR, f);
      expect(statSync(p).isFile()).toBe(true);
    }
  });

  it("blinky.kicad_pro is valid JSON with the expected top-level keys", () => {
    const raw = readFileSync(
      resolve(BLINKY_DIR, "blinky.kicad_pro"),
      "utf8",
    );
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    for (const key of [
      "board",
      "libraries",
      "meta",
      "net_settings",
      "schematic",
      "text_variables",
    ]) {
      expect(parsed).toHaveProperty(key);
    }
  });

  it("blinky.kicad_pcb starts with `(kicad_pcb` and includes the ESP32 footprint", () => {
    const raw = readFileSync(
      resolve(BLINKY_DIR, "blinky.kicad_pcb"),
      "utf8",
    );
    expect(raw.startsWith("(kicad_pcb")).toBe(true);
    expect(raw).toContain("MCU_Espressif:ESP32-S3-WROOM-1");
    expect(raw).toContain("Capacitor_SMD:C_0603_1608Metric");
  });

  it("Project synthesized from the blinky on-disk data satisfies the KCIR Project shape", () => {
    const pro = JSON.parse(
      readFileSync(resolve(BLINKY_DIR, "blinky.kicad_pro"), "utf8"),
    ) as {
      meta: { filename: string };
      net_settings: { classes: Array<{ name: string; clearance: number; track_width: number; via_diameter: number; via_drill: number }> };
      board: { design_settings: { rules: { min_clearance: number; min_track_width: number; min_via_diameter: number; min_via_drill: number } } };
      schematic: { top_level_sheets: Array<{ filename: string; name: string; uuid: string }> };
      libraries: { pinned_symbol_libs: string[]; pinned_footprint_libs: string[] };
    };

    const topSheet = pro.schematic.top_level_sheets[0];
    const cls = pro.net_settings.classes[0];
    const rules = pro.board.design_settings.rules;

    const project: Project = {
      kcir_version: "0.1.0",
      name: pro.meta.filename.replace(/\.kicad_pro$/, ""),
      schematic: {
        sheets: [
          {
            uuid: topSheet.uuid,
            name: topSheet.name,
            file: topSheet.filename,
            parent: null,
            position_mm: [0, 0],
            size_mm: [0, 0],
            pins: [],
          },
        ],
        symbols: [],
        wires: [],
        junctions: [],
        labels: [],
        no_connects: [],
        buses: [],
        lib_symbols: [],
      },
      pcb: {
        version: 20240108,
        generator: "kiclaude",
        thickness_mm: 1.6,
        paper: "A4",
        pad_to_mask_clearance_mm: 0,
        layers: [
          { id: 0, name: "F.Cu", kind: "signal", purpose: "user" },
          { id: 31, name: "B.Cu", kind: "signal", purpose: "user" },
          { id: 44, name: "Edge.Cuts", kind: "user", purpose: "user" },
        ],
        footprints: [
          {
            uuid: "5c7e0a3e-4f9b-4ddc-9b3d-0001000000a1",
            refdes: "U1",
            lib_id: "MCU_Espressif:ESP32-S3-WROOM-1",
            value: "ESP32-S3-WROOM-1",
            mpn: "",
            layer: "F.Cu",
            position_mm: [50, 50],
            rotation_deg: 0,
            locked: false,
          },
          {
            uuid: "5c7e0a3e-4f9b-4ddc-9b3d-0001000000c1",
            refdes: "C1",
            lib_id: "Capacitor_SMD:C_0603_1608Metric",
            value: "100nF",
            mpn: "",
            layer: "F.Cu",
            position_mm: [70, 50],
            rotation_deg: 0,
            locked: false,
          },
        ],
        tracks: [],
        vias: [],
        zones: [],
        outline: {
          points_mm: [
            [0, 0],
            [100, 0],
            [100, 100],
            [0, 100],
          ],
          cutouts: [],
        },
        drawings: [],
        nets: [
          {
            name: "",
            class: cls.name,
            members: [],
            diff_pair: null,
            power_rail: null,
            topology: null,
            length_match_group: null,
            target_impedance_ohm: null,
            reference_plane: null,
          },
          {
            name: "GND",
            class: cls.name,
            members: [],
            diff_pair: null,
            power_rail: "GND",
            topology: null,
            length_match_group: null,
            target_impedance_ohm: null,
            reference_plane: null,
          },
        ],
      },
      libraries: {
        symbol_libs: pro.libraries.pinned_symbol_libs.map((n) => ({
          name: n,
          uri: `\${KICAD9_SYMBOL_DIR}/${n}.kicad_sym`,
          kind: "KiCad",
          options: "",
          descr: "",
        })),
        footprint_libs: pro.libraries.pinned_footprint_libs.map((n) => ({
          name: n,
          uri: `\${KICAD9_FOOTPRINT_DIR}/${n}.pretty`,
          kind: "KiCad",
          options: "",
          descr: "",
        })),
      },
      stackup: {
        layers: [
          { name: "F.Cu", kind: "copper", thickness_mm: 0.035, dielectric_constant: null, loss_tangent: null, color: "copper" },
          { name: "core", kind: "dielectric", thickness_mm: 1.53, dielectric_constant: 4.5, loss_tangent: 0.02, color: "" },
          { name: "B.Cu", kind: "copper", thickness_mm: 0.035, dielectric_constant: null, loss_tangent: null, color: "copper" },
        ],
        power_plane_layers: [],
        controlled_impedance: false,
        board_thickness_mm: 1.6,
        finish: "HASL",
      },
      design_rules: {
        clearance_mm: rules.min_clearance,
        trace_width_mm: rules.min_track_width,
        via_drill_mm: rules.min_via_drill,
        via_diameter_mm: rules.min_via_diameter,
        uvia_drill_mm: 0.1,
        uvia_diameter_mm: 0.2,
        allow_microvias: false,
        allow_blind_buried_vias: false,
      },
      net_classes: [
        {
          name: cls.name,
          description: "",
          clearance_mm: cls.clearance,
          trace_width_mm: cls.track_width,
          via_drill_mm: cls.via_drill,
          via_diameter_mm: cls.via_diameter,
          diff_pair_width_mm: null,
          diff_pair_gap_mm: null,
        },
      ],
      fab_target: null,
      bom_policy: {
        preferred_distributors: [],
        max_unit_price_usd: null,
        require_in_stock: false,
        require_jlc_assembly: false,
        region: "US",
      },
      metadata: {
        title: "blinky",
        revision: "0.1",
        company: "",
        date: "",
        comment_1: "",
        comment_2: "",
        comment_3: "",
        comment_4: "",
      },
    };

    // The compile-time `Project` annotation already gates the
    // structural fit; verify the leaf values round-trip JSON intact.
    const cloned = JSON.parse(JSON.stringify(project)) as Project;
    expect(cloned.name).toBe("blinky");
    expect(cloned.schematic.sheets).toHaveLength(1);
    expect(cloned.schematic.sheets[0].uuid).toBe(topSheet.uuid);
    expect(cloned.pcb.footprints).toHaveLength(2);
    expect(cloned.pcb.footprints[0].refdes).toBe("U1");
    expect(cloned.pcb.footprints[1].refdes).toBe("C1");
    expect(cloned.pcb.layers.map((l) => l.name)).toEqual([
      "F.Cu",
      "B.Cu",
      "Edge.Cuts",
    ]);
    expect(cloned.net_classes[0].name).toBe("Default");
    expect(cloned.design_rules.clearance_mm).toBe(rules.min_clearance);

    // Deep equality after round-trip — catches accidental class
    // instances (Date, BigInt, etc.) sneaking into KCIR.
    expect(cloned).toEqual(project);
  });
});
