// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A board layer — copper, dielectric, soldermask, silkscreen, etc.
 */
export type Layer = { 
/**
 * `KiCad` layer id — 0 = F.Cu, 31 = B.Cu, 32+ = user / mask / paste.
 */
id: number, name: string, 
/**
 * `signal`, `power`, `mixed`, `jumper`, `user`.
 */
kind: string, 
/**
 * Optional display name (e.g. `"B.Adhesive"`).
 */
purpose: string, };
