// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A board layer — copper, dielectric, soldermask, silkscreen, etc.
 */
export type Layer = { id: number, name: string, kind: string, purpose: string, };
