// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named length-match group.
 */
export type LengthGroup = { 
/**
 * Display name (e.g. `"DDR3_DQ_BYTE0"`, `"RGMII_TX"`).
 */
name: string, 
/**
 * Net names that belong to this group. The analyzer walks each
 * net's track polylines to compute the running total length.
 */
nets: Array<string>, 
/**
 * Target length in mm. `0.0` = "match the longest net";
 * > 0 = explicit target the analyzer drives every member to.
 */
target_length_mm: number, 
/**
 * Tolerance (mm) — nets within `±tolerance_mm` of the target are
 * considered matched. Typical values: 0.127 mm (5 mil) for diff
 * pairs, 0.5 mm for parallel buses below 800 Mbps.
 */
tolerance_mm: number, };
