// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryEntry } from "./LibraryEntry";

/**
 * Aggregated library table (symbol libs + footprint libs).
 */
export type LibraryTable = { symbol_libs: Array<LibraryEntry>, footprint_libs: Array<LibraryEntry>, };
