// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single library row, mirroring a `sym-lib-table` / `fp-lib-table` entry.
 */
export type LibraryEntry = { name: string, uri: string, 
/**
 * Library kind — typically "`KiCad`", "Legacy", or "Cloud".
 */
kind: string, options: string, descr: string, };
