// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `(model "<path>" …)` — a 3D model the renderer can mount on the pad.
 */
export type Model3D = { path: string, offset_mm: [number, number, number], scale: [number, number, number], rotate_deg: [number, number, number], };
