// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable bundle of per-net constraints (width, clearance, via size).
 */
export type NetClass = { name: string, description: string, clearance_mm: number, trace_width_mm: number, via_drill_mm: number, via_diameter_mm: number, diff_pair_width_mm: number | null, diff_pair_gap_mm: number | null, };
