// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PadRef } from "./PadRef";

/**
 * A no-connect marker on a symbol pin or floating wire end.
 */
export type NoConnect = { uuid: string, sheet_uuid: string, 
/**
 * On-sheet position of the marker.
 */
position_mm: [number, number], 
/**
 * Optional reference to the pad the no-connect attaches to.
 * Populated by M1-R-05's connectivity pass; empty until then.
 */
at: PadRef, };
