// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerRef } from "./LayerRef";

/**
 * One pad on a [`FootprintInstance`].
 */
export type Pad = { 
/**
 * `KiCad`'s pad number — usually `"1"`, `"GND"`, etc. Not unique
 * across the board; combine with the parent's `refdes` for a
 * project-wide id.
 */
number: string, 
/**
 * `smd`, `thru_hole`, `connect`, `np_thru_hole`.
 */
pad_type: string, 
/**
 * `rect`, `circle`, `oval`, `roundrect`, `trapezoid`, `custom`.
 */
shape: string, 
/**
 * Pad center in the parent footprint's local frame, mm.
 */
position_mm: [number, number], 
/**
 * Rotation in degrees relative to the parent footprint.
 */
rotation_deg: number, 
/**
 * `(size W H)` — copper extent in mm.
 */
size_mm: [number, number], 
/**
 * `(drill D)` for through-hole pads, or `(drill oval W H)`.
 */
drill_mm: [number, number] | null, 
/**
 * Layers the pad lives on (`F.Cu`, `*.Cu`, `F.Mask`, …).
 */
layers: Array<LayerRef>, 
/**
 * `(net N "<name>")` — the resolved net name, or empty for NC.
 */
net: string, 
/**
 * `(roundrect_rratio R)` — corner radius ratio for rounded
 * rectangle pads.
 */
roundrect_rratio: number | null, 
/**
 * `(uuid …)` — opaque per-instance identifier.
 */
uuid: string, };
