// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a specific pad on a footprint, e.g. `U1.7`.
 */
export type PadRef = { refdes: string, pad: string, };
