// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffPair } from "./DiffPair";
import type { Drawing } from "./Drawing";
import type { FootprintInstance } from "./FootprintInstance";
import type { Layer } from "./Layer";
import type { LengthGroup } from "./LengthGroup";
import type { Net } from "./Net";
import type { NetClass } from "./NetClass";
import type { Outline } from "./Outline";
import type { Signoff } from "./Signoff";
import type { Track } from "./Track";
import type { Via } from "./Via";
import type { Zone } from "./Zone";

/**
 * The PCB view of a [`Project`](super::Project).
 */
export type Pcb = { 
/**
 * `(version YYYYMMDD)` — the `KiCad` `.kicad_pcb` schema stamp.
 */
version: number, 
/**
 * `(generator <name>)` — name of the tool that last wrote this file.
 */
generator: string, 
/**
 * `(general (thickness X))` — total board thickness in mm.
 */
thickness_mm: number, 
/**
 * `(paper "<format>")` — page size for plotted output.
 */
paper: string, 
/**
 * `(setup (pad_to_mask_clearance X))` — pad-to-mask clearance in mm.
 */
pad_to_mask_clearance_mm: number, 
/**
 * `(setup (solder_mask_min_width X))` — minimum sliver between mask
 * openings before `KiCad` merges them.
 */
solder_mask_min_width_mm: number, 
/**
 * Per-PCB `(net_class …)` declarations.
 */
net_classes: Array<NetClass>, layers: Array<Layer>, footprints: Array<FootprintInstance>, tracks: Array<Track>, vias: Array<Via>, zones: Array<Zone>, outline: Outline, drawings: Array<Drawing>, nets: Array<Net>, 
/**
 * M3-R-07 — declared differential pairs. Drives the diff-pair
 * router (M3-R-04) and the impedance solver (M3-R-02).
 */
diff_pairs: Array<DiffPair>, 
/**
 * M3-R-07 — declared length-match groups. Drives the
 * length-match analyzer + tuning queue (M3-R-05).
 */
length_groups: Array<LengthGroup>, 
/**
 * M5 / KC060 + KC070 design sign-off gates. Each flag is a
 * deliberate human review gate; the high-speed validators emit
 * warnings until the matching flag is set. **The LLM cannot flip
 * these** — a `PreToolUse` hook in `services/agent` rejects any
 * Claude-originated mutation that targets `pcb.signoff.*`.
 */
signoff: Signoff, };
