// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BomPolicy } from "./BomPolicy";
import type { DesignRules } from "./DesignRules";
import type { FabTarget } from "./FabTarget";
import type { LibraryTable } from "./LibraryTable";
import type { NetClass } from "./NetClass";
import type { Pcb } from "./Pcb";
import type { ProjectMetadata } from "./ProjectMetadata";
import type { Schematic } from "./Schematic";
import type { Stackup } from "./Stackup";

/**
 * A kiclaude project — the in-memory equivalent of a `KiCad` project on
 * disk (`.kicad_pro` + `.kicad_sch` + `.kicad_pcb` + library tables).
 *
 * See `docs/specs/SPEC-01-kiclaude.md` §7.2 for field semantics.
 */
export type Project = { 
/**
 * KCIR schema version (semver string). See `KCIR_VERSION` in `lib.rs`.
 */
kcir_version: string, 
/**
 * Human-readable project name. Mirrors the `.kicad_pro` `meta.filename`
 * stem and the schematic title block.
 */
name: string, 
/**
 * Schematic view (multi-sheet hierarchy of symbols, wires, labels).
 */
schematic: Schematic, 
/**
 * PCB view (footprints, tracks, vias, zones, layers).
 */
pcb: Pcb, 
/**
 * Resolved library table for symbols + footprints.
 */
libraries: LibraryTable, 
/**
 * Physical layer stackup.
 */
stackup: Stackup, 
/**
 * Design rules (clearance, trace widths, drill sizes).
 */
design_rules: DesignRules, 
/**
 * Per-class net constraints. Mirrors `(net_class …)` in `.kicad_pcb`.
 */
net_classes: Array<NetClass>, 
/**
 * Selected fab target preset, if any.
 */
fab_target: FabTarget | null, 
/**
 * BOM sourcing policy.
 */
bom_policy: BomPolicy, 
/**
 * Title block + free-form metadata.
 */
metadata: ProjectMetadata, };
