// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bus } from "./Bus";
import type { Junction } from "./Junction";
import type { Label } from "./Label";
import type { LibSymbol } from "./LibSymbol";
import type { NoConnect } from "./NoConnect";
import type { Sheet } from "./Sheet";
import type { SymbolInstance } from "./SymbolInstance";
import type { Wire } from "./Wire";

/**
 * A schematic view of a [`Project`](super::Project) — a forest of sheets.
 */
export type Schematic = { 
/**
 * All sheets in declaration order. `sheets[0]` is conventionally
 * the root; multi-sheet hierarchy resolution lands in M1-R-05.
 */
sheets: Array<Sheet>, symbols: Array<SymbolInstance>, wires: Array<Wire>, junctions: Array<Junction>, labels: Array<Label>, no_connects: Array<NoConnect>, buses: Array<Bus>, 
/**
 * Library symbol definitions inlined at the top of each
 * `.kicad_sch`. De-duplicated by `lib_id` across sheets.
 */
lib_symbols: Array<LibSymbol>, };
