// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pin on a sub-sheet block — the in/out connection from the parent
 * sheet to a hierarchical label inside the child sheet.
 */
export type SheetPin = { uuid: string, name: string, 
/**
 * `input` | `output` | `bidirectional` | `tri_state` | `passive`.
 */
shape: string, position_mm: [number, number], rotation_deg: number, };
