// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SheetPin } from "./SheetPin";

/**
 * A single sheet within the schematic hierarchy.
 *
 * Top-level (root) sheets have `parent = None`. Sub-sheets reference
 * their parent via uuid. The on-canvas placement fields
 * ([`position_mm`](Self::position_mm) / [`size_mm`](Self::size_mm))
 * are only meaningful for sub-sheets — the root sheet leaves them
 * at zero.
 */
export type Sheet = { uuid: string, name: string, file: string, parent: string | null, 
/**
 * On-canvas position of the sub-sheet block on the parent sheet.
 */
position_mm: [number, number], 
/**
 * On-canvas size of the sub-sheet block on the parent sheet.
 */
size_mm: [number, number], 
/**
 * Hierarchical pins that connect this sub-sheet to its parent.
 */
pins: Array<SheetPin>, };
