// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-board human review sign-off flags (SPEC §11 M5).
 *
 * These gate the advanced-workflow validators:
 * - `ddr_reviewed` clears [KC060](crate) (DDR fly-by topology).
 * - `bga_fanout_reviewed` clears [KC070](crate) (BGA fanout DFM).
 * - `rf_reviewed` clears RF/CPWG review (M5 co-pilot).
 *
 * Default is "nothing reviewed" — every flag starts `false`, so a
 * freshly-opened board surfaces the M5 validators as warnings until a
 * human ticks the box in the UI. Claude is forbidden from setting them
 * (enforced by the agent's permission gate), keeping sign-off a human
 * act.
 */
export type Signoff = { 
/**
 * RF / antenna / CPWG feed reviewed by a human EE.
 */
rf_reviewed: boolean, 
/**
 * DDR fly-by topology reviewed and accepted (clears KC060).
 */
ddr_reviewed: boolean, 
/**
 * BGA fanout feasibility reviewed and accepted (clears KC070).
 */
bga_fanout_reviewed: boolean, };
