// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a layer is made of.
 */
export type StackupLayerKind = "copper" | "dielectric" | "soldermask" | "silkscreen" | "paste" | "adhesive";
