// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StackupLayer } from "./StackupLayer";

/**
 * The physical layer/dielectric stackup. Defaults to a 2-layer FR-4
 * preset, which is the M2 demo target.
 */
export type Stackup = { layers: Array<StackupLayer>, power_plane_layers: Array<string>, controlled_impedance: boolean, board_thickness_mm: number, finish: string, };
