// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StackupLayerKind } from "./StackupLayerKind";

/**
 * A single layer in the stackup.
 */
export type StackupLayer = { name: string, kind: StackupLayerKind, thickness_mm: number, dielectric_constant: number | null, loss_tangent: number | null, color: string, };
