// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerRef } from "./LayerRef";

/**
 * A copper zone (polygon pour) bound to a net.
 */
export type Zone = { uuid: string, layer: LayerRef, net: string, outline_mm: Array<[number, number]>, thermal_relief: boolean, };
