import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { expect, test } from "@playwright/test";

/**
 * M2-Q-04 — frame-timing benchmark for NFR-003.
 *
 * Loads the synthesised dense board (1000 footprints + 5000 tracks,
 * generated by `tests/perf/generate_dense_board.py`) into the
 * React PcbCanvas, then samples `requestAnimationFrame` callbacks
 * for `SAMPLE_DURATION_MS` to compute mean and p95 frame durations.
 * The resulting median FPS is asserted against two tiers per
 * spec §11 NFR-003:
 *
 *   - **discrete-GPU runner**: ≥ 60 FPS median
 *   - **integrated-GPU runner**: ≥ 30 FPS median
 *
 * Set `PERF_GPU=discrete` (default) or `PERF_GPU=integrated` to
 * pick the bar. CI runners pass the appropriate value via env.
 *
 * Output: a JSON blob is written to
 * `tests/perf/results/pcb_render_<timestamp>.json` so CI can ship
 * it as an artifact for regression tracking. The same blob is
 * attached to the Playwright report for easy inspection.
 *
 * Gates:
 *   - `tests/perf/dense_board.kicad_pcb` must exist (generate it
 *     via the Python script — the spec calls `test.skip` if it's
 *     missing rather than re-generating from JS, since the
 *     generator depends on the Python `uv` environment).
 *   - The client dev server's project picker must accept a path
 *     param so the spec can drive directly to the dense board
 *     without manual clicks. We probe and `test.skip` if it
 *     isn't there.
 */

const SAMPLE_DURATION_MS = 5_000;
const WARMUP_MS = 1_000;
const DISCRETE_TARGET_FPS = 60;
const INTEGRATED_TARGET_FPS = 30;

const REPO_ROOT = (() => {
  try {
    return execSync("git rev-parse --show-toplevel", {
      encoding: "utf-8",
      cwd: process.cwd(),
    }).trim();
  } catch {
    return "";
  }
})();

const GPU_TIER = (process.env.PERF_GPU ?? "discrete").toLowerCase();
const TARGET_FPS =
  GPU_TIER === "integrated" ? INTEGRATED_TARGET_FPS : DISCRETE_TARGET_FPS;

interface FrameSample {
  /** Wall-clock ms since the previous animation frame. */
  delta_ms: number;
}

interface BenchmarkResult {
  spec: string;
  gpu_tier: "discrete" | "integrated";
  target_fps: number;
  sample_count: number;
  /** Median FPS across the sampling window. */
  median_fps: number;
  /** 95th-percentile frame duration in ms. Lower is better. */
  p95_ms: number;
  /** Mean frame duration in ms. */
  mean_ms: number;
  ts: string;
  warmup_ms: number;
  duration_ms: number;
  fixture: string;
}

test.describe("M2-Q-04 PCB render benchmark (NFR-003)", () => {
  test.beforeAll(({}, testInfo) => {
    const fixture = join(REPO_ROOT, "tests", "perf", "dense_board.kicad_pcb");
    if (!existsSync(fixture)) {
      testInfo.skip(
        true,
        `tests/perf/dense_board.kicad_pcb missing — run \`uv run python ` +
          `tests/perf/generate_dense_board.py\` first`,
      );
    }
  });

  test(`renders 1000 footprints / 5000 tracks at ≥ ${TARGET_FPS} FPS (${GPU_TIER})`, async ({
    page,
  }, testInfo) => {
    test.setTimeout(60_000);
    await page.goto("/?perf=1");

    // Probe for the project-picker URL-param entry point. If absent,
    // we cannot reliably drive to the dense board, and the
    // benchmark is meaningless without it.
    const canvas = page.locator(
      "[data-testid='pcb-canvas'][data-status='ready']",
    );
    if (
      (await page.getByTestId("project-picker").count()) === 0 &&
      (await canvas.count()) === 0
    ) {
      testInfo.skip(
        true,
        "neither project-picker nor an already-loaded PcbCanvas " +
          "appeared — wire `?fixture=dense_board.kicad_pcb` " +
          "for headless benchmarking",
      );
      return;
    }

    // If the picker is up, open the dense fixture through it.
    if ((await page.getByTestId("project-picker").count()) > 0) {
      await page.getByTestId("project-picker").click();
      const option = page.getByText("dense_board", { exact: false });
      if ((await option.count()) > 0) {
        await option.click();
      } else {
        testInfo.skip(
          true,
          "project-picker does not list dense_board — register " +
            "it under client/src/lib/perf-fixtures.ts",
        );
        return;
      }
    }
    await page.waitForSelector(
      "[data-testid='pcb-canvas'][data-status='ready']",
      { timeout: 30_000 },
    );

    // Warm-up: ignore initial frames where shader compile + texture
    // upload skew the per-frame cost.
    await page.waitForTimeout(WARMUP_MS);

    // Drive a pan/zoom interaction during sampling so the renderer
    // actually re-issues draw calls instead of sitting idle.
    const samples = await page.evaluate(
      async ({ duration }) => {
        const out: number[] = [];
        let last = performance.now();
        await new Promise<void>((resolve) => {
          const start = performance.now();
          function tick(now: number) {
            out.push(now - last);
            last = now;
            // Synthesise a tiny pan to keep the GPU under load.
            const evt = new WheelEvent("wheel", {
              deltaY: -10,
              clientX: window.innerWidth / 2,
              clientY: window.innerHeight / 2,
              bubbles: true,
            });
            document
              .querySelector("[data-testid='pcb-canvas']")
              ?.dispatchEvent(evt);
            if (now - start >= duration) {
              resolve();
              return;
            }
            requestAnimationFrame(tick);
          }
          requestAnimationFrame(tick);
        });
        return out;
      },
      { duration: SAMPLE_DURATION_MS },
    );

    expect(samples.length).toBeGreaterThan(0);
    const result = summarise(samples, GPU_TIER);
    expect(
      result.median_fps,
      `dense board rendered at ${result.median_fps.toFixed(1)} FPS (median) ` +
        `vs ${TARGET_FPS} FPS target on a ${GPU_TIER}-GPU runner`,
    ).toBeGreaterThanOrEqual(TARGET_FPS);

    // Persist + attach the benchmark for CI tracking.
    const resultsDir = join(REPO_ROOT, "tests", "perf", "results");
    mkdirSync(resultsDir, { recursive: true });
    const fname = `pcb_render_${result.ts}.json`;
    writeFileSync(join(resultsDir, fname), JSON.stringify(result, null, 2));
    testInfo.attachments.push({
      name: "pcb_render_benchmark.json",
      contentType: "application/json",
      body: Buffer.from(JSON.stringify(result, null, 2)),
    });
  });
});

function summarise(
  rawSamples: number[],
  gpuTier: string,
): BenchmarkResult {
  const samples: FrameSample[] = rawSamples
    .filter((d) => d > 0 && d < 1_000)
    .map((delta_ms) => ({ delta_ms }));
  const deltas = samples.map((s) => s.delta_ms).sort((a, b) => a - b);
  const median =
    deltas.length === 0
      ? 0
      : deltas[Math.floor(deltas.length / 2)] ?? 0;
  const p95 =
    deltas.length === 0
      ? 0
      : deltas[Math.floor(deltas.length * 0.95)] ?? deltas[deltas.length - 1] ?? 0;
  const mean =
    deltas.length === 0
      ? 0
      : deltas.reduce((sum, d) => sum + d, 0) / deltas.length;
  return {
    spec: "M2-Q-04 pcb_render",
    gpu_tier: gpuTier === "integrated" ? "integrated" : "discrete",
    target_fps:
      gpuTier === "integrated" ? INTEGRATED_TARGET_FPS : DISCRETE_TARGET_FPS,
    sample_count: samples.length,
    median_fps: median > 0 ? 1000 / median : 0,
    p95_ms: p95,
    mean_ms: mean,
    ts: new Date().toISOString().replace(/[:.]/g, "-"),
    warmup_ms: WARMUP_MS,
    duration_ms: SAMPLE_DURATION_MS,
    fixture: "tests/perf/dense_board.kicad_pcb",
  };
}
