// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * BOM sourcing policy — how `kc_bom_price` should choose distributors and
 * parts. Filled out in M3.
 */
export type BomPolicy = { preferred_distributors: Array<string>, max_unit_price_usd: number | null, require_in_stock: boolean, require_jlc_assembly: boolean, region: string, };
