// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Design rule check thresholds. Mirrors `(design_settings …)` in
 * `.kicad_pcb` for the bits kiclaude consumes directly.
 */
export type DesignRules = { clearance_mm: number, trace_width_mm: number, via_drill_mm: number, via_diameter_mm: number, uvia_drill_mm: number, uvia_diameter_mm: number, allow_microvias: boolean, allow_blind_buried_vias: boolean, };
