// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelKind } from "./LabelKind";

/**
 * A net label attached to a wire.
 */
export type Label = { uuid: string, sheet_uuid: string, kind: LabelKind, text: string, position_mm: [number, number], rotation_deg: number, 
/**
 * `input` | `output` | `bidirectional` | `tri_state` | `passive`.
 * Set for global / hierarchical labels; empty for local labels.
 */
shape: string, };
