// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminator for the four `KiCad` label flavors.
 */
export type LabelKind = "local" | "global" | "hierarchical" | "power";
