// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolProperty } from "./SymbolProperty";

/**
 * A library symbol definition inlined at the top of a `.kicad_sch`.
 *
 * `KiCad` bundles every symbol definition used by a sheet so the file
 * is self-contained even if the originating library is unavailable.
 * M1-R-04 reads the on-disk `.kicad_sym` libraries; this struct
 * captures the inlined cache so a round-trip can preserve symbols
 * that no longer exist on disk.
 */
export type LibSymbol = { lib_id: string, properties: Array<SymbolProperty>, 
/**
 * True if the symbol comes from the `power:` library namespace.
 */
is_power: boolean, };
