// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerRef } from "./LayerRef";
import type { NetClassRef } from "./NetClassRef";
import type { NetRef } from "./NetRef";
import type { PadRef } from "./PadRef";
import type { Topology } from "./Topology";

/**
 * A net — a set of pads electrically tied together. See SPEC §7.2.
 */
export type Net = { name: string, class: NetClassRef, members: Array<PadRef>, diff_pair: NetRef | null, power_rail: string | null, topology: Topology | null, length_match_group: string | null, target_impedance_ohm: number | null, reference_plane: LayerRef | null, };
