// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The board outline (Edge.Cuts polygon).
 */
export type Outline = { points_mm: Array<[number, number]>, cutouts: Array<Array<[number, number]>>, };
