// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Drawing } from "./Drawing";
import type { FootprintInstance } from "./FootprintInstance";
import type { Layer } from "./Layer";
import type { Net } from "./Net";
import type { Outline } from "./Outline";
import type { Track } from "./Track";
import type { Via } from "./Via";
import type { Zone } from "./Zone";

/**
 * The PCB view of a [`Project`](super::Project).
 */
export type Pcb = { 
/**
 * `(version YYYYMMDD)` — the `KiCad` `.kicad_pcb` schema stamp.
 */
version: number, 
/**
 * `(generator <name>)` — name of the tool that last wrote this file.
 */
generator: string, 
/**
 * `(general (thickness X))` — total board thickness in mm.
 */
thickness_mm: number, 
/**
 * `(paper "<format>")` — page size for plotted output.
 */
paper: string, 
/**
 * `(setup (pad_to_mask_clearance X))` — pad-to-mask clearance in mm.
 * Stored on `Pcb` because M0-R-06 emit round-trip requires preserving
 * it; richer setup options land in M2.
 */
pad_to_mask_clearance_mm: number, layers: Array<Layer>, footprints: Array<FootprintInstance>, tracks: Array<Track>, vias: Array<Via>, zones: Array<Zone>, outline: Outline, drawings: Array<Drawing>, nets: Array<Net>, };
