// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `KiCad`-style title block plus extension fields.
 */
export type ProjectMetadata = { title: string, revision: string, company: string, date: string, comment_1: string, comment_2: string, comment_3: string, comment_4: string, };
