// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolProperty } from "./SymbolProperty";

/**
 * An instance of a library symbol placed on a sheet.
 *
 * Carries six independent boolean flags (`mirrored`, `in_bom`,
 * `on_board`, `dnp`, `is_power_flag`, `is_power_symbol`) — each
 * surfaces a separate `KiCad`-defined concept that callers query
 * individually, so packing them behind a bitset would only hide the
 * names.
 */
export type SymbolInstance = { uuid: string, sheet_uuid: string, lib_id: string, refdes: string, value: string, footprint: string, mpn: string, datasheet: string, position_mm: [number, number], rotation_deg: number, mirrored: boolean, 
/**
 * Multi-unit symbols (e.g. a quad-NAND has 4 units); 1-based. The
 * emitter writes `(unit 1)` for single-unit symbols.
 */
unit: number, 
/**
 * True if this symbol should appear on the BOM. `KiCad` default: true.
 */
in_bom: boolean, 
/**
 * True if this symbol should appear on the PCB netlist. Default: true.
 */
on_board: boolean, 
/**
 * "Do Not Populate" — included in the BOM but flagged.
 */
dnp: boolean, 
/**
 * True for `power:PWR_FLAG` instances — they're net markers, not
 * real components. Detected by [`crate::format::v9::sch::map_sch`]
 * from the symbol's `lib_id`.
 */
is_power_flag: boolean, 
/**
 * True if this symbol is a power-net symbol from the `KiCad`
 * `power` library (e.g. `power:GND`, `power:VCC`). Power symbols
 * are implicit net labels rather than physical components.
 */
is_power_symbol: boolean, 
/**
 * Every `(property "Key" "Value" …)` form on this instance, in
 * declaration order. Includes the standard fields
 * (`Reference`, `Value`, `Footprint`, `Datasheet`, `MPN`) — those
 * are also surfaced as the named fields above for ergonomics.
 */
properties: Array<SymbolProperty>, };
