// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `(property "Key" "Value" (at x y rot) (effects …))` form attached
 * to a [`SymbolInstance`] or [`LibSymbol`].
 */
export type SymbolProperty = { key: string, value: string, 
/**
 * Position offset on the sheet. Zero if the property has no `(at …)`.
 */
position_mm: [number, number], rotation_deg: number, 
/**
 * True if the property is rendered as hidden in the editor.
 */
hide: boolean, };
