// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Net topology constraint — applied to address/data buses and similar.
 */
export type Topology = "daisy_chain" | "fly_by" | "star" | "bus";
