// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A straight wire segment between two points on a sheet.
 */
export type Wire = { uuid: string, sheet_uuid: string, points_mm: Array<[number, number]>, };
