/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Endpoint */
        get: operations["version_endpoint_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Endpoint
         * @description Validate an uploaded CIR YAML/.ato. Returns full board summary +
         *     validation report so the viewer can render everything from one call.
         */
        post: operations["validate_endpoint_api_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cir
         * @description Return the working CIR file: its text plus parsed/validated state.
         */
        get: operations["get_cir_api_cir_get"];
        /**
         * Put Cir
         * @description Replace the working CIR file.
         *
         *     Rejects (400) text that won't parse — a syntactically broken file is
         *     never written to disk, so the working copy always stays loadable.
         */
        put: operations["put_cir_api_cir_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cir/signoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Cir Signoff
         * @description Apply a partial sign-off update to the working CIR (SPEC-1 G4).
         *
         *     Only fields the client explicitly sets are written; unset fields keep
         *     their on-disk values. Re-emits the canonical YAML through the same
         *     helper the form PUT uses so the round-trip stays byte-identical.
         */
        patch: operations["patch_cir_signoff_api_cir_signoff_patch"];
        trace?: never;
    };
    "/api/cir/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Cir Board
         * @description Replace the working CIR from a structured ``Board`` JSON (SPEC-1 G3).
         *
         *     The form editor sends a full ``Board`` object; FastAPI validates it via
         *     Pydantic, the canonical YAML is emitted and persisted, and the same
         *     ``CirState`` the text path returns is returned. A field-validation
         *     failure surfaces as 422 (FastAPI's standard validation error shape) so
         *     the form can highlight the offending fields.
         */
        put: operations["put_cir_board_api_cir_board_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace
         * @description Return the working directory the backend is currently using.
         */
        get: operations["get_workspace_api_workspace_get"];
        put?: never;
        /**
         * Set Workspace
         * @description Persist a new working directory.
         *
         *     The path must be **absolute** and refer to an existing directory; we
         *     reject relative paths and non-directory targets with 400 so the GUI
         *     can show a clear error rather than the launcher silently picking a
         *     nonsense default on the next start.
         */
        post: operations["set_workspace_api_workspace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse_intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Intent Endpoint
         * @description Natural-language description → draft CIR (SPEC-1 FR-5).
         *
         *     Wraps ``ki_mcp_pcb_core.parsers.nl.parse_nl``. The draft is *not*
         *     written to the working CIR — the GUI shows it to the user first; they
         *     accept by PUTting the text through ``/api/cir`` themselves. On a
         *     missing Anthropic SDK / API key the endpoint surfaces 503 with the
         *     structured detail so the dialog can show "configure Anthropic to use
         *     intent-to-CIR" rather than a generic 500.
         */
        post: operations["parse_intent_endpoint_api_parse_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Doctor
         * @description Environment health — which pipeline stages can run on this machine.
         */
        get: operations["get_doctor_api_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Build
         * @description Run the full pipeline on the working CIR; return the per-stage result.
         */
        post: operations["post_build_api_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/build/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build Stream
         * @description Run the pipeline, streaming one SSE ``stage`` event per stage.
         *
         *     The synchronous ``pipeline.build`` runs in a worker thread; its
         *     ``on_stage`` callback feeds a thread-safe queue the async generator
         *     drains. The stream ends with a ``done`` (or ``error``) event.
         */
        get: operations["build_stream_api_build_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description List every generated file under the working build directory.
         */
        get: operations["list_artifacts_api_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Download one build artifact.
         *
         *     The resolved target must stay inside the build directory — a path that
         *     escapes it (``..`` traversal) is rejected with 404.
         */
        get: operations["get_artifact_api_artifacts__artifact_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diff Endpoint */
        post: operations["diff_endpoint_api_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diff/working": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff Working Endpoint
         * @description Diff an uploaded baseline against the working CIR (SPEC-1 G3-T2).
         *
         *     The GUI's diff view always reads the right-hand side from the on-disk
         *     working CIR, so it only needs to upload the baseline. The baseline is
         *     treated as the *left* board (the "before"), the working CIR as the
         *     *right* (the "after").
         */
        post: operations["diff_working_endpoint_api_diff_working_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decoupling_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decoupling Check Endpoint
         * @description Decoupling-coverage check (CIR030) over the working CIR.
         *
         *     Mirrors the MCP ``tool_decoupling_check`` shape: ``ok`` is False when
         *     any CIR030 issue is an error, plus the list of components that *did*
         *     declare ``decoupling_pins`` for the GUI to render alongside the issues.
         */
        get: operations["decoupling_check_endpoint_api_decoupling_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/return_path_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return Path Check Endpoint
         * @description Return-path check (CIR090) over the working CIR.
         *
         *     Mirrors the MCP ``tool_return_path_check`` shape and adds the list of
         *     nets whose return path the check applies to (high-speed / differential
         *     / RF, or any net that names a reference plane).
         */
        get: operations["return_path_check_endpoint_api_return_path_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/impedance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Impedance Endpoint
         * @description Per-net achievable Zo for every net with a target_impedance_ohm
         *     (file-upload form — the GUI uses ``/api/impedance/working`` instead).
         */
        post: operations["impedance_endpoint_api_impedance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/impedance/working": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Impedance Working Endpoint
         * @description Per-net achievable Zo for the working CIR (SPEC-1 G3 result pane).
         */
        get: operations["impedance_working_endpoint_api_impedance_working_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Artifact
         * @description One generated file in the build directory.
         */
        Artifact: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Size */
            size: number;
        };
        /** BOMPolicy */
        BOMPolicy: {
            /** Distributors */
            distributors?: ("digikey" | "mouser" | "jlc" | "lcsc" | "octopart")[];
            /**
             * Require In Stock
             * @default true
             */
            require_in_stock: boolean;
            /** Max Unit Price Usd */
            max_unit_price_usd?: number | null;
            /**
             * Prefer Basic Parts
             * @description JLC 'basic' parts avoid the assembly fee.
             * @default true
             */
            prefer_basic_parts: boolean;
        };
        /**
         * BOMRow
         * @description One line in the BOM CSV.
         *
         *     Mirrors the JLCPCB-style columns: Comment, Designator, Footprint,
         *     LCSC, MPN. ``lcsc`` is filled by the sourcing layer when present.
         */
        BOMRow: {
            /** Comment */
            comment: string;
            /** Designator */
            designator: string;
            /** Footprint */
            footprint: string;
            /** Mpn */
            mpn: string;
            /** Lcsc */
            lcsc?: string | null;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /**
         * Board
         * @description The top-level CIR document — one board per file.
         */
        Board: {
            /**
             * Cir Version
             * @default 0.4
             */
            cir_version: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            stackup?: components["schemas"]["Stackup"];
            outline?: components["schemas"]["Outline"];
            /** Components */
            components?: components["schemas"]["Component"][];
            /** Nets */
            nets?: components["schemas"]["Net"][];
            /** Constraints */
            constraints?: components["schemas"]["Constraint"][];
            fab?: components["schemas"]["FabTarget"];
            bom_policy?: components["schemas"]["BOMPolicy"];
            signoff?: components["schemas"]["Signoff"];
        };
        /** Body_diff_endpoint_api_diff_post */
        Body_diff_endpoint_api_diff_post: {
            /** Left */
            left: string;
            /** Right */
            right: string;
        };
        /** Body_diff_working_endpoint_api_diff_working_post */
        Body_diff_working_endpoint_api_diff_working_post: {
            /** Baseline */
            baseline: string;
        };
        /** Body_impedance_endpoint_api_impedance_post */
        Body_impedance_endpoint_api_impedance_post: {
            /** File */
            file: string;
        };
        /** Body_validate_endpoint_api_validate_post */
        Body_validate_endpoint_api_validate_post: {
            /** File */
            file: string;
        };
        /**
         * BuildRequest
         * @description Request body for ``POST /api/build``.
         */
        BuildRequest: {
            /**
             * Run Route
             * @default false
             */
            run_route: boolean;
        };
        /**
         * BuildResponse
         * @description The full pipeline result — every stage plus the output directory.
         */
        BuildResponse: {
            /** Ok */
            ok: boolean;
            /** Stages */
            stages: components["schemas"]["StageResult"][];
            /** Out Dir */
            out_dir: string;
        };
        /**
         * CirState
         * @description The working-CIR API payload: raw text plus parsed/validated state.
         *
         *     ``board``/``bom``/``sourcing`` are passed through as loose JSON (the
         *     GUI renders them); ``parse_error`` / ``validation`` are what the GUI
         *     branches on, so they are precisely typed.
         */
        CirState: {
            /** Exists */
            exists: boolean;
            /** Text */
            text: string;
            /** Parse Error */
            parse_error: string | null;
            /** Board */
            board: {
                [key: string]: unknown;
            } | null;
            validation: components["schemas"]["ValidationSummary"] | null;
            /** Bom */
            bom: components["schemas"]["BOMRow"][];
            /** Sourcing */
            sourcing: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CirText
         * @description Request body for ``PUT /api/cir`` — the raw CIR YAML text.
         */
        CirText: {
            /** Text */
            text: string;
        };
        /**
         * Component
         * @description A placed (or to-be-placed) electrical component.
         */
        Component: {
            /**
             * Refdes
             * @description Reference designator (e.g. 'R1', 'U2', 'C42').
             */
            refdes: string;
            /**
             * Mpn
             * @description Manufacturer part number — must resolve at synthesis time.
             */
            mpn: string;
            /** Value */
            value?: string | null;
            /**
             * Footprint
             * @description KiCad footprint identifier 'Library:Name'. If None, the synthesizer resolves it from MPN.
             */
            footprint?: string | null;
            /**
             * Symbol
             * @description KiCad symbol identifier 'Library:Name'. If None, resolved from MPN.
             */
            symbol?: string | null;
            /**
             * Placement Hint
             * @description Declarative natural-language placement hint, e.g. 'south edge, centered'. Never raw coordinates from an LLM.
             */
            placement_hint?: string | null;
            /**
             * Partition
             * @description Mixed-signal partition this component belongs to. Validators (CIR050) enforce no signal nets cross partitions except via declared bridge components.
             */
            partition?: ("analog" | "digital" | "rf" | "power" | "isolated") | null;
            /**
             * Decoupling Pins
             * @description Supply pin numbers that require nearby decoupling. Used by the M2 decoupling-coverage validator (CIR030).
             */
            decoupling_pins?: string[];
            /**
             * Is Bridge
             * @description Marks a component as a partition bridge (ferrite bead, opto-isolator, capacitor coupling). Bridges may legally connect different partitions.
             * @default false
             */
            is_bridge: boolean;
            /**
             * Bga Pitch Mm
             * @description Ball pitch in mm for BGA / LGA packages (typically 0.4 / 0.5 / 0.65 / 0.8 / 1.0). CIR110 looks up the fanout template for the declared pitch and warns if the current fab target can't escape-route it.
             */
            bga_pitch_mm?: number | null;
            /** Attrs */
            attrs?: {
                [key: string]: string;
            };
        };
        /**
         * ComponentChangeRow
         * @description One per-component field-level change row in a structured diff.
         */
        ComponentChangeRow: {
            /** Refdes */
            refdes: string;
            /** Field */
            field: string;
            /** Left */
            left: string | null;
            /** Right */
            right: string | null;
        };
        /**
         * Constraint
         * @description A design-intent constraint that the validator will enforce.
         */
        Constraint: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "max_length" | "min_length" | "length_match" | "min_separation" | "max_stub" | "decoupling_within_mm" | "keep_out" | "controlled_impedance";
            /**
             * Targets
             * @description Net names, net classes, or refdes the constraint applies to.
             */
            targets?: string[];
            /** Value Mm */
            value_mm?: number | null;
            /** Value Ohm */
            value_ohm?: number | null;
            /** Tolerance Pct */
            tolerance_pct?: number | null;
            /** Note */
            note?: string | null;
        };
        /**
         * DecouplingCheckResponse
         * @description ``/api/decoupling_check`` payload — CIR030 issues + GUI context.
         */
        DecouplingCheckResponse: {
            /** Ok */
            ok: boolean;
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Ics With Decoupling Declared */
            ics_with_decoupling_declared: string[];
        };
        /**
         * DiffResponse
         * @description Structured CIR diff — shared by ``/api/diff`` and ``/api/diff/working``.
         */
        DiffResponse: {
            /** Identical */
            identical: boolean;
            /** Summary */
            summary: string;
            /** Name Changed */
            name_changed: [
                string,
                string
            ] | null;
            /** Components Added */
            components_added: string[];
            /** Components Removed */
            components_removed: string[];
            /** Component Changes */
            component_changes: components["schemas"]["ComponentChangeRow"][];
            /** Nets Added */
            nets_added: string[];
            /** Nets Removed */
            nets_removed: string[];
            /** Net Changes */
            net_changes: components["schemas"]["NetChangeRow"][];
        };
        /**
         * DoctorCheck
         * @description One environment-health probe (kicad-cli, pcbnew, Freerouting, …).
         */
        DoctorCheck: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
        };
        /**
         * FabTarget
         * @description Target fabrication house + its DFM constraints.
         */
        FabTarget: {
            /**
             * Name
             * @default jlcpcb
             * @enum {string}
             */
            name: "jlcpcb" | "oshpark" | "pcbway" | "generic";
            /**
             * Min Trace Mm
             * @description Distance in millimeters.
             * @default 0.127
             */
            min_trace_mm: number;
            /**
             * Min Space Mm
             * @description Distance in millimeters.
             * @default 0.127
             */
            min_space_mm: number;
            /**
             * Min Drill Mm
             * @description Distance in millimeters.
             * @default 0.2
             */
            min_drill_mm: number;
            /**
             * Min Annular Ring Mm
             * @description Distance in millimeters.
             * @default 0.13
             */
            min_annular_ring_mm: number;
            /**
             * Layer Count
             * @default 2
             */
            layer_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HighSpeedNet
         * @description A net whose return path the CIR090 check applies to.
         */
        HighSpeedNet: {
            /** Net */
            net: string;
            /** Net Class */
            net_class: string;
            /** Reference Plane */
            reference_plane: string | null;
        };
        /**
         * ImpedanceResponse
         * @description ``/api/impedance`` / ``/api/impedance/working`` payload.
         */
        ImpedanceResponse: {
            /** Rows */
            rows: components["schemas"]["ImpedanceRow"][];
        };
        /**
         * ImpedanceRow
         * @description One net's target vs achieved impedance, plus the trace geometry.
         */
        ImpedanceRow: {
            /** Net */
            net: string;
            /** Target Ohm */
            target_ohm: number;
            /** Achieved Ohm */
            achieved_ohm: number | null;
            /** Trace Width Mm */
            trace_width_mm: number | null;
            /** Trace Spacing Mm */
            trace_spacing_mm: number | null;
            /** Cpwg Gap Mm */
            cpwg_gap_mm: number | null;
            /** Diff Pair With */
            diff_pair_with: string | null;
        };
        /**
         * IntentRequest
         * @description Request body for ``POST /api/parse_intent``.
         */
        IntentRequest: {
            /** Text */
            text: string;
        };
        /**
         * Layer
         * @description A single copper or dielectric layer.
         */
        Layer: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "copper" | "dielectric" | "soldermask" | "silkscreen" | "paste";
            /**
             * Thickness Mm
             * @description Distance in millimeters.
             * @default 0.035
             */
            thickness_mm: number;
            /** Material */
            material?: string | null;
            /**
             * Er
             * @description Relative permittivity for dielectric layers.
             */
            er?: number | null;
        };
        /**
         * Net
         * @description A named electrical net.
         */
        Net: {
            /** Name */
            name: string;
            /**
             * Members
             * @description List of 'REFDES.PIN' strings (e.g. 'U1.3', 'R5.2').
             */
            members?: string[];
            /**
             * Net Class
             * @default signal
             * @enum {string}
             */
            net_class: "signal" | "power" | "ground" | "high_speed" | "differential" | "rf" | "analog";
            /** Length Match Group */
            length_match_group?: string | null;
            /** Target Impedance Ohm */
            target_impedance_ohm?: number | null;
            /**
             * Power Rail
             * @description Which power rail this net belongs to (e.g. '3V3', 'VBUS'). Used by the decoupling-coverage validator to match supply pins.
             */
            power_rail?: string | null;
            /**
             * Partition
             * @description Mixed-signal partition this net belongs to. CIR050 enforces signal nets stay within a partition.
             */
            partition?: ("analog" | "digital" | "rf" | "power" | "isolated") | null;
            /**
             * Cross Partition Ok
             * @description Marks a partition crossing as intentional (e.g. an I2S or SPI bus that legitimately bridges digital ↔ analog ICs). Set this only when the crossing has been reviewed.
             * @default false
             */
            cross_partition_ok: boolean;
            /**
             * Diff Pair With
             * @description Name of the other net in this differential pair. CIR060 validates that the named net exists, points back at us, and shares a length-match group. USB D+/D−, Ethernet TX±/RX±.
             */
            diff_pair_with?: string | null;
            /**
             * Reference Plane
             * @description Stackup layer name (e.g. 'In1.Cu') that this net's return current should travel on. CIR090 checks the plane exists in the stackup and is contiguous (not split under the trace).
             */
            reference_plane?: string | null;
            /**
             * Trace Width Mm
             * @description Per-net trace width override. Used by the impedance solver (CIR070) when set; otherwise a conservative default is applied. Diff pairs and controlled-impedance nets typically need this set explicitly.
             */
            trace_width_mm?: number | null;
            /**
             * Trace Spacing Mm
             * @description Per-net edge-to-edge spacing for differential pairs. Only used when ``diff_pair_with`` is also set.
             */
            trace_spacing_mm?: number | null;
            /**
             * Cpwg Gap Mm
             * @description Trace-to-side-ground gap for grounded coplanar waveguide (CPWG) RF nets. CIR070 calls the CPWG solver when this is set instead of the microstrip approximation.
             */
            cpwg_gap_mm?: number | null;
            /**
             * Topology
             * @description Routing topology hint. DDR3/4 address+command nets are typically 'fly_by' (controller → ram_0 → ram_1 → … → terminator).
             */
            topology?: ("point_to_point" | "fly_by" | "t_branch" | "star") | null;
            /**
             * Fly By Order
             * @description Ordered list of refdes for fly-by topology — first entry is the controller, last entry is the terminator. CIR100 enforces the order and structure.
             */
            fly_by_order?: string[];
        };
        /**
         * NetChangeRow
         * @description One per-net field-level change row in a structured diff.
         */
        NetChangeRow: {
            /** Name */
            name: string;
            /** Field */
            field: string;
            /** Left */
            left: string;
            /** Right */
            right: string;
        };
        /**
         * Outline
         * @description Board outline. ``auto`` lets the placement step infer a rectangle.
         */
        Outline: {
            /**
             * Shape
             * @default auto
             * @enum {string}
             */
            shape: "auto" | "rect" | "polygon";
            /** Width Mm */
            width_mm?: number | null;
            /** Height Mm */
            height_mm?: number | null;
            /** Polygon Mm */
            polygon_mm?: [
                number,
                number
            ][] | null;
            /**
             * Corner Radius Mm
             * @description Distance in millimeters.
             * @default 0
             */
            corner_radius_mm: number;
        };
        /**
         * ParseIntentResponse
         * @description The intent→CIR draft — what the GUI's IntentDialog previews.
         */
        ParseIntentResponse: {
            board: components["schemas"]["Board"];
            /** Draft Yaml */
            draft_yaml: string;
        };
        /**
         * ReturnPathCheckResponse
         * @description ``/api/return_path_check`` payload — CIR090 issues + GUI context.
         */
        ReturnPathCheckResponse: {
            /** Ok */
            ok: boolean;
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** High Speed Nets */
            high_speed_nets: components["schemas"]["HighSpeedNet"][];
        };
        /**
         * Signoff
         * @description Co-pilot acknowledgment for high-stakes M4 features.
         *
         *     When set ``True``, suppresses the "needs human review" warnings the
         *     M4 validators emit. This is the audit trail: an LLM cannot flip these
         *     flags on its own — a human must commit the change.
         */
        Signoff: {
            /**
             * Rf Reviewed
             * @description RF traces / antennas have been reviewed by a human EE
             * @default false
             */
            rf_reviewed: boolean;
            /**
             * Ddr Reviewed
             * @description DDR fly-by topology + length tuning reviewed
             * @default false
             */
            ddr_reviewed: boolean;
            /**
             * Bga Fanout Reviewed
             * @description BGA escape routing reviewed
             * @default false
             */
            bga_fanout_reviewed: boolean;
            /**
             * Reviewer
             * @description Name/handle of the human reviewer
             */
            reviewer?: string | null;
            /**
             * Reviewed At
             * @description ISO 8601 date the review was completed
             */
            reviewed_at?: string | null;
        };
        /**
         * SignoffPatch
         * @description Partial sign-off update — only the fields the GUI sent get applied.
         *
         *     SPEC-1 / CLAUDE.md: only a human may flip a ``Board.signoff.*`` flag.
         *     The GUI dispatches this PATCH directly (no agent path goes through
         *     here); the agent's only way to touch sign-off is to Write/Edit the CIR
         *     file, which is already gated by ``can_use_tool`` (G2).
         */
        SignoffPatch: {
            /** Rf Reviewed */
            rf_reviewed?: boolean | null;
            /** Ddr Reviewed */
            ddr_reviewed?: boolean | null;
            /** Bga Fanout Reviewed */
            bga_fanout_reviewed?: boolean | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
        };
        /**
         * Stackup
         * @description PCB layer stackup.
         *
         *     For M1 the default was 2-layer FR-4. M2 introduces 4-layer with
         *     power planes via ``default_4layer_fr4``. M3+ adds controlled-impedance
         *     hints for high-speed work.
         */
        Stackup: {
            /** Layers */
            layers: components["schemas"]["Layer"][];
            /**
             * Finished Thickness Mm
             * @description Distance in millimeters.
             * @default 1.6
             */
            finished_thickness_mm: number;
            /**
             * Controlled Impedance
             * @default false
             */
            controlled_impedance: boolean;
            /** Power Plane Layers */
            power_plane_layers?: string[];
        };
        /**
         * StageResult
         * @description One pipeline stage's outcome.
         */
        StageResult: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Where */
            where?: string | null;
        };
        /**
         * ValidationSummary
         * @description Flattened validation outcome — the GUI gates on ``ok``.
         */
        ValidationSummary: {
            /** Ok */
            ok: boolean;
            /** Errors */
            errors: number;
            /** Warnings */
            warnings: number;
            /** Issues */
            issues: {
                [key: string]: unknown;
            }[];
        };
        /**
         * WorkspaceState
         * @description Where the working directory is right now + how it was chosen.
         *
         *     ``source`` lets the GUI render the right control: a persisted choice
         *     can be replaced; the env-override case is read-only with a hint to
         *     unset ``KIMP_GUI_WORKDIR`` to regain GUI control.
         */
        WorkspaceState: {
            /** Path */
            path: string;
            /**
             * Source
             * @enum {string}
             */
            source: "env" | "persisted" | "default";
        };
        /**
         * WorkspaceUpdate
         * @description Request body for ``POST /api/workspace`` — the new absolute path.
         */
        WorkspaceUpdate: {
            /** Path */
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    version_endpoint_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    validate_endpoint_api_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_endpoint_api_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cir_api_cir_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CirState"];
                };
            };
        };
    };
    put_cir_api_cir_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CirText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CirState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_cir_signoff_api_cir_signoff_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignoffPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CirState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_cir_board_api_cir_board_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Board"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CirState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
        };
    };
    set_workspace_api_workspace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_intent_endpoint_api_parse_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseIntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor_api_doctor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorCheck"][];
                };
            };
        };
    };
    post_build_api_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_stream_api_build_stream_get: {
        parameters: {
            query?: {
                run_route?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
        };
    };
    get_artifact_api_artifacts__artifact_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_endpoint_api_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_diff_endpoint_api_diff_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_working_endpoint_api_diff_working_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_diff_working_endpoint_api_diff_working_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decoupling_check_endpoint_api_decoupling_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecouplingCheckResponse"];
                };
            };
        };
    };
    return_path_check_endpoint_api_return_path_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnPathCheckResponse"];
                };
            };
        };
    };
    impedance_endpoint_api_impedance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_impedance_endpoint_api_impedance_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpedanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    impedance_working_endpoint_api_impedance_working_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpedanceResponse"];
                };
            };
        };
    };
}
